Fix cleanup type issues with non-sqlite backends
We store the data as strings, so when telling SQL to compare, we should be
sending strings to compare against.
SQLite does not actually check types, so doesn't throw this error, but for
example in Postgres, the following error is being recorded:
ProgrammingError: (psycopg2.ProgrammingError) operator does not exist: text <= timestamp without time zone

Merges: #120
Signed-off-by: Patrick Uiterwijk <puiterwijk@redhat.com>
Reviewed-by: Pierre-Yves Chibon <pingou@pingoured.fr>
Reviewed-by: Howard Johnson <merlin@merlinthp.org>